application: lunchdiscuss
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
  
- url: /images
  static_dir: images

- url: .*
  script: main.py
  login: required
