application: lunchdiscuss
version: groups
runtime: python
api_version: 1

inbound_services:
- mail

handlers:
- url: /static
  static_dir: static
  
- url: /images
  static_dir: images

- url: .*
  script: main.py
  login: required


