application: lunchdiscuss
version: cirdep-fix 
runtime: python
api_version: 1

inbound_services:
- mail

handlers:
- url: /static
  static_dir: static
  
- url: /images
  static_dir: images

- url: /_ah/mail/.+
  script: emailhandler.py

- url: /cron/.+
  script: cron.py

- url: .*
  script: main.py
  login: required


